apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-manager-ingress
  annotations:
    # מאפשר לפרונטאנד ולבקאנד לעבוד יחד ללא בעיות ניתוב
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx # <-- השורה הקריטית שמחברת את ה-Ingress ל-NGINX שהתקנת!
  rules:
    - http:
        paths:
          # 1. ניתוב עבור ה-Backend (כל מה שמתחיל ב- /api)
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3001
          # 2. ניתוב עבור ה-Frontend (כל שאר הבקשות)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000